name: state-forecasting

channels:
  - conda-forge

dependencies:
  - r-base>=4.3
  - r-irkernel
  - r-tidyverse
  - r-ggplot2
  - r-readr
  - r-dplyr
  - r-tidyr
  - r-scales
  - r-tibble
  - jupyterlab